name: Auto Reply and Delete Comments

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull_requests: write

jobs:
  auto-reply-delete:
    runs-on: ubuntu-latest

    steps:
      - name: Filter, Reply to, and Delete Comments
        uses: actions/github-script@v6
        with:
          script: |
            const triggerPhrases = ["can i work on this issue", "assign this to me"];
            const commentBody = context.payload.comment.body.toLowerCase();
            const commenter = context.payload.comment.user.login;

            if (triggerPhrases.some(phrase => commentBody.includes(phrase))) {
              // Delete the comment
              await github.rest.issues.deleteComment({
                comment_id: context.payload.comment.id,
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              // Reply to the comment with guidelines
              await github.rest.issues.createComment({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `@${commenter} Please read the contribution guide before commenting.`
              });
            }
